x-app-environment: &app-environment
  HOST: "${HOST:?HOST is not set}"
  DOMAIN: "${DOMAIN:?DOMAIN is not set}"
  BACKEND_PORT: "${BACKEND_PORT:?BACKEND_PORT is not set}"
  CALLS_PORT: "${CALLS_PORT:?CALLS_PORT is not set}"
  FRONTEND_PORT: "${FRONTEND_PORT:?FRONTEND_PORT is not set}"
  DB_PATH: "${DB_PATH:?DB_PATH is not set}"
  CALLS_URL: "${CALLS_URL:?CALLS_URL is not set}"
  SESSION_DURATION: "${SESSION_DURATION:?SESSION_DURATION is not set}"
  REQUEST_INTERVAL: "${REQUEST_INTERVAL:?REQUEST_INTERVAL is not set}"

services:
  ved3v-backend:
    image: http://registry-gitlab.shtab.digital/internal/mir-messenger:production
    container_name: ved3v-backend
    command: python -m backend.backend_main
    restart: unless-stopped
    environment: *app-environment
    volumes:
      - ./data:/app/data
    working_dir: /app
    networks:
      - web

  ved3v-calls:
    image: http://registry-gitlab.shtab.digital/internal/mir-messenger:production
    container_name: ved3v-calls
    command: python -m tests.calls_websockets_test.server
    restart: unless-stopped
    environment: *app-environment
    working_dir: /app
    networks:
      - web

  ved3v-frontend:
    image: http://registry-gitlab.shtab.digital/internal/mir-messenger:production
    container_name: ved3v-frontend
    command: python -m frontend.frontend_main
    restart: unless-stopped
    environment: *app-environment
    working_dir: /app
    depends_on:
      - ved3v-backend
    networks:
      - web

networks:
  web:
    external: true
