services:
  ved3v-backend:
    build: .
    container_name: ved3v-backend
    command: python -m backend.backend_main
    restart: unless-stopped
    #ports:
    #  - "0.0.0.0:8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    working_dir: /app
    networks:
      - web

  ved3v-calls:
    build: .
    container_name: ved3v-calls
    command: python -m tests.calls_websockets_test.server
    restart: unless-stopped
    working_dir: /app
    networks:
      - web

  ved3v-frontend:
    build: .
    container_name: ved3v-frontend
    command: python -m frontend.frontend_main
    restart: unless-stopped
    #ports:
    #  - "0.0.0.0:3000:3000"
    env_file:
      - .env
    working_dir: /app
    depends_on:
      - ved3v-backend
    networks:
      - web

networks:
  web:
    external: true
